In [67]:
import cv2

In [68]:
cv2.VideoCapture(0)

< cv2.VideoCapture 0000024BE1B5A350>

In [69]:
cap = cv2.VideoCapture(0)

In [70]:
status , photo = cap.read()

In [71]:
status

True

In [72]:
photo

array([[[138, 111, 109],
        [136, 108, 111],
        [135, 105, 115],
        ...,
        [ 81,  53,  57],
        [ 84,  55,  60],
        [ 84,  55,  60]],

       [[134, 106, 108],
        [130, 100, 107],
        [132, 102, 116],
        ...,
        [ 84,  56,  63],
        [ 86,  57,  62],
        [ 81,  53,  57]],

       [[133, 101, 104],
        [135, 101, 109],
        [136, 100, 115],
        ...,
        [ 92,  62,  72],
        [ 79,  55,  64],
        [ 78,  53,  62]],

       ...,

       [[ 74,  44,  58],
        [ 75,  43,  53],
        [ 81,  48,  53],
        ...,
        [113,  59,  55],
        [110,  56,  52],
        [104,  51,  46]],

       [[ 74,  44,  58],
        [ 83,  51,  63],
        [102,  68,  78],
        ...,
        [107,  53,  49],
        [104,  51,  46],
        [104,  51,  46]],

       [[ 77,  46,  60],
        [ 92,  58,  70],
        [109,  71,  81],
        ...,
        [106,  53,  49],
        [107,  53,  49],
        [107,  53,  49]]

In [40]:
photo.ndim

3

In [41]:
status


True

In [75]:
cap.release()

In [13]:
a = numpy.array([12,3,4,5,6])

In [12]:
import numpy

In [14]:
a

array([12,  3,  4,  5,  6])

In [15]:
a = numpy.array(
    [
        [1,10,100],
        [2,20,200],
        [3,30,300],
        [4,40,400]
    ])

In [16]:
a.shape

(4, 3)

In [17]:
a[1:3, 1:3] = 5

In [18]:
a.shape

(4, 3)

In [24]:
a

array([[  1,  10, 100],
       [  2,   5,   5],
       [  3,   5,   5],
       [  4,  40, 400]])

In [43]:
a[: , :  ]

array([[  1,  10, 100],
       [  2,   5,   5],
       [  3,   5,   5],
       [  4,  40, 400]])

In [56]:
# in photo first is row , second is column, 
photo[10, 30]

array([198, 175,   0], dtype=uint8)

In [57]:
photo[10, 30]

array([198, 175,   0], dtype=uint8)

In [58]:
status

True

In [74]:
cv2.imshow("hi", photo)

In [51]:
photo[10, 30, 2] = 0

In [1]:
# if we put some intelligent on the top of machine learning is known computer vision
# let's put some intelligent on the top of image or put AI 
#on the top of image we have to use IA who help you



In [2]:
# Haarcascode

In [3]:
import cv2

In [5]:
cap = cv2.VideoCapture(0)

In [6]:
status, photo

NameError: name 'status' is not defined

In [7]:
cv2.CascadeClassifier("")

SystemError: <class 'cv2.CascadeClassifier'> returned a result with an exception set